export const projects = [
  {
    title: 'Multiverse',
    description: "Social Sharing Image Platform",
      image: 'https://media.giphy.com/media/JRthPrTuebsuX0jGGg/giphy.gif',
      tags: ['NEXT.JS', 'TAILWIND', 'SANITY', 'GOOGLE'],
    source: 'https://github.com/JohnMaturan97/Multiverse',
    visit: 'https://multiverse101.netlify.app/login',
    id: 1,
  },
    {
    title: 'Genisys',
    description: "Online Movies and TV Shows Platform",
      image: 'https://media.giphy.com/media/c7pAcTuoJfuJawWEVv/giphy.gif',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/JohnMaturan97/Genisys',
    visit: 'https://genenisys.netlify.app/',
    id: 2,
  },
  {
    title: 'Codeverse',
    description:"Social Sharing Platform built with MERN stack and Socket.io for real-time chat and notifications. Other Developtment Tools used : HTML5, CSS3, Redux, Hooks, Semantic-UI, and Infinite Scroll.",
    image: 'https://media.giphy.com/media/b6EZlVdLbLI0pH647j/giphy.gif',
    tags: ['Javascript','Next.js', 'Node.js','Express', 'Mongo',],
    source: 'https://github.com/JohnMaturan97/Codverse-main',
    visit: 'https://codeverse-network-site.herokuapp.com/login',
    id: 3,
  },
  {
    title: '30MinutesOrLess',
    description: "Full Stack (MERN) Pizza/Wing Delivery web application built using React for front end, Redux-Thunk for asynchronous operations, Node.js for runtime envrionment, Express.js for backend routing, and MongoDB for database.",
      image: 'https://media.giphy.com/media/RJ8udsHIjhpPBM2lsJ/giphy.gif',
      tags: ['Javascript','React', 'Node.js','Express', 'Mongo',],
    source: 'https://github.com/JohnMaturan97/30MinutesOrLess',
    visit: 'https://latenight-30minutesorless.herokuapp.com/',
    id: 4,
  },
  {
    title: 'Atomy',
    description: "A Full Stack web application where users can register or sign in by using google authentication, shop online with its fully responsive design by using CSS/SCSS, Javascript, React/Router, Redux, Hooks and Stripe for payments.",
    image: 'https://media.giphy.com/media/3ove5ORM7hgBpgpwSo/giphy.gif',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/JohnMaturan97/Atomy_Online_Store',
    visit: 'https://atomy-store-live.herokuapp.com/',
    id: 5,
  },
  {
    title: 'BugChat',
    description: "Real-time Chat Application with google and facebook authentications.",
    image: 'https://media.giphy.com/media/WIGcNLR8N5z2GRDm4L/giphy.gif',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/JohnMaturan97/BugChat',
    visit: 'https://bugchat.netlify.app/',
    id: 6,
  },
  // {
  //   title: 'Organization',
  //   description: "Simple React Project made by HTML5 / CSS3 / Javascript / REACT.",
  //   image: 'https://media.giphy.com/media/W2q1ZNYbi1Kdwc9iLP/giphy.gif',
  //   tags: ['HTML5','CSS3','Javascript', 'React'],
  //   source: 'https://github.com/JohnMaturan97/Java_Coders',
  //   visit: 'https://johnmaturan97.github.io/Java_Coders/',
  //   id: 7,
  // },
  // {
  //   title: 'Github',
  //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   image: 'https://media.giphy.com/media/W2q1ZNYbi1Kdwc9iLP/giphy.gif',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 8,
  // },
  // {
  //   title: 'Unichat',
  //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 3,
  // },
  // {
  //   title: 'Unichat',
  //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 3,
  // },
];

export const TimeLineData = [
  { year: 2016, text: 'Enlisted to the United States Army', },
  { year: 2019, text: 'Fall - Enrolled to the University of North Carolina at Charlotte', },
  { year: 2019, text: 'Fall - Re-enlisted to join the Army National Guard', },
  { year: 2021, text: 'Summer - Enrolled into Claim Academy Bootcamp', },
  { year: 2021, text: 'Fall - Solution Analyst at Deloitte', },
];