export const projects = [
  // {
  //   title: 'BornToCode Academy',
  //   description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
  //     image: 'https://media.giphy.com/media/b6EZlVdLbLI0pH647j/giphy.gif',
  //     tags: ['Mongo', 'Express', 'React', 'Node'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 0,
  // },
  {
    title: 'Codeverse',
    description:"Social Sharing Platform built with MERN stack and Socket.io for real-time chat and notifications. Other Developtment Tools used : HTML5, CSS3, Redux, Hooks, Semantic-UI, and Infinite Scroll.",
    image: 'https://media.giphy.com/media/b6EZlVdLbLI0pH647j/giphy.gif',
    tags: ['Javascript','Next.js', 'Node.js','Express', 'Mongo',],
    source: 'https://github.com/JohnMaturan97/Codverse-main',
    visit: 'https://codeverse-network-site.herokuapp.com/login',
    id: 1,
  },
  {
    title: '30MinutesOrLess',
    description: "Full Stack (MERN) Pizza/Wing Delivery web application built using React for front end, Redux-Thunk for asynchronous operations, Node.js for runtime envrionment, Express.js for backend routing, and MongoDB for database.",
      image: 'https://media.giphy.com/media/RJ8udsHIjhpPBM2lsJ/giphy.gif',
      tags: ['Javascript','React', 'Node.js','Express', 'Mongo',],
    source: 'https://github.com/JohnMaturan97/30MinutesOrLess',
    visit: 'https://latenight-30minutesorless.herokuapp.com/',
    id: 2,
  },
  {
    title: 'Atomy',
    description: "A Full Stack web application where users can register or sign in by using google authentication, shop online with its fully responsive design by using CSS/SCSS, Javascript, React/Router, Redux, Hooks and Stripe for payments.",
    image: 'https://media.giphy.com/media/3ove5ORM7hgBpgpwSo/giphy.gif',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/JohnMaturan97/Atomy_Online_Store',
    visit: 'https://atomy-store-live.herokuapp.com/',
    id: 3,
  },
  {
    title: 'BugChat',
    description: "Real-time Chat Application with google and facebook authentications.",
    image: 'https://media.giphy.com/media/WIGcNLR8N5z2GRDm4L/giphy.gif',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/JohnMaturan97/BugChat',
    visit: 'https://bugchat.netlify.app/',
    id: 3,
  },
  {
    title: 'JavaCoders',
    description: "Simple React Project made by HTML5 / CSS3 / Javascript / REACT.",
    image: 'https://media.giphy.com/media/W2q1ZNYbi1Kdwc9iLP/giphy.gif',
    tags: ['HTML5','CSS3','Javascript', 'React'],
    source: 'https://github.com/JohnMaturan97/Java_Coders',
    visit: 'https://johnmaturan97.github.io/Java_Coders/',
    id: 3,
  },
  // {
  //   title: 'Unichat',
  //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 3,
  // },
  // {
  //   title: 'Unichat',
  //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 3,
  // },
  // {
  //   title: 'Unichat',
  //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 3,
  // },
];

export const TimeLineData = [
  { year: 2016, text: 'Enlisted to the United States Army', },
  { year: 2019, text: 'Enrolled to the University of North Carolina at Charlotte', },
  { year: 2019, text: 'Re-enlisted to join the Army National Guard', },
  { year: 2021, text: 'Enrolled into Claim Academy Bootcamp', },
];